const motivation = [
    { line: "You're making a difference every day. Thank you!" },
    { line: "Your hard work is appreciated. Keep it up!" },
    { line: "Thanks for ensuring our safety on the road!" },
    { line: "Your dedication shines through every ride." },
    { line: "You keep us moving forward. Thanks a lot!" },
    { line: "Your reliability means the world to us." },
    { line: "Great job keeping us safe and on time!" },
    { line: "Your work is essential. Thank you!" },
    { line: "We appreciate your commitment every day." },
    { line: "Thanks for being a dependable driver!" },
    { line: "Your professionalism is inspiring." },
    { line: "Thanks for your daily dedication!" },
    { line: "Your hard work doesn't go unnoticed." },
    { line: "Thank you for your constant care." },
    { line: "Your effort keeps us on track." },
    { line: "We trust in your excellent service." },
    { line: "Your work is crucial. Thanks a lot!" },
    { line: "Thanks for your unwavering commitment!" },
    { line: "Your dedication keeps us moving." },
    { line: "Thanks for making every journey safe!" },
    { line: "Your smile brightens our day!" },
    { line: "You bring joy to our rides." },
    { line: "Thanks for your positive attitude!" },
    { line: "Your patience is admirable." },
    { line: "Your kindness makes a big difference." },
    { line: "You're a great role model!" },
    { line: "Thanks for your professionalism!" },
    { line: "Your hard work is truly inspiring." },
    { line: "You're doing an amazing job!" },
    { line: "Thanks for your outstanding service!" },
    { line: "Your dedication is second to none." },
    { line: "Thanks for always going the extra mile!" },
    { line: "You are a valued team member." },
    { line: "Your efforts make a huge impact." },
    { line: "Thanks for your constant support!" },
    { line: "Your commitment is appreciated." },
    { line: "Thanks for being so reliable!" },
    { line: "You're an essential part of our team." },
    { line: "Your dedication is unmatched." },
    { line: "Thanks for your consistent effort!" },
    { line: "Your hard work is making a difference." },
    { line: "We appreciate all that you do!" },
    { line: "Thanks for your tireless work!" },
    { line: "You're a key player in our success." },
    { line: "Thanks for always being on time!" },
    { line: "Your dedication keeps us going." },
    { line: "Thanks for your amazing attitude!" },
    { line: "Your hard work is the foundation of our success." },
    { line: "Thanks for your perseverance!" },
    { line: "You're a great asset to our team!" },
    { line: "Thanks for your ongoing commitment!" },
    { line: "Your work is truly valued." },
    { line: "Thanks for your attention to detail!" },
    { line: "Your positive attitude is contagious." },
    { line: "Thanks for always doing your best!" },
    { line: "Your hard work does not go unnoticed." },
    { line: "Thanks for your reliability!" },
    { line: "You're a true professional." },
    { line: "Thanks for your excellent service!" },
    { line: "Your dedication is inspiring." },
    { line: "Thanks for always being dependable!" },
    { line: "You're an amazing driver." },
    { line: "Thanks for your constant effort!" },
    { line: "Your hard work is essential." },
    { line: "Thanks for your dedication to safety!" },
    { line: "Your professionalism is top-notch." },
    { line: "Thanks for your great work!" },
    { line: "You're a valued member of our team." },
    { line: "Thanks for your consistent hard work!" },
    { line: "Your reliability is appreciated." },
    { line: "Thanks for your dedication to excellence!" },
    { line: "You're making a positive impact." },
    { line: "Thanks for always being there!" },
    { line: "Your hard work is the backbone of our success." },
    { line: "Thanks for your unwavering dedication!" },
    { line: "You're a true asset to our team." },
    { line: "Thanks for your commitment to quality!" },
    { line: "Your effort is greatly appreciated." },
    { line: "Thanks for your fantastic work!" },
    { line: "You're a model of excellence." },
    { line: "Thanks for your dedication to our team!" },
    { line: "Your hard work is greatly valued." },
    { line: "Thanks for your reliability and professionalism!" },
    { line: "You're making a significant difference." },
    { line: "Thanks for your outstanding commitment!" },
    { line: "Your hard work is the key to our success." },
    { line: "Thanks for your consistent excellence!" },
    { line: "You're a driving force behind our success." },
    { line: "Thanks for your unwavering support!" },
    { line: "Your dedication is truly appreciated." },
    { line: "Thanks for always giving your best!" },
    { line: "Your hard work is the heart of our team." },
    { line: "Thanks for your exceptional effort!" },
    { line: "You're an inspiration to us all." },
    { line: "Thanks for your commitment to our success!" },
    { line: "Your work is truly valuable." },
    { line: "Thanks for being an amazing driver!" },
    { line: "Your hard work is the foundation of our team." },
    { line: "Thanks for your dedication and effort!" }
];

export default motivation;
